//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPortfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AboutsDiv
    {
        public int Id { get; set; }
        public string Photo { get; set; }
        public Nullable<int> aboutItemID { get; set; }
    
        public virtual AboutItems AboutItems { get; set; }
    }
}
